# Generated by Django 4.1.2 on 2022-10-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
