# Generated by Django 4.1.2 on 2022-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_question_user_delete_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pub_date',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='user',
            name='infection_probabilty',
            field=models.FloatField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
