# Generated by Django 4.1.2 on 2022-10-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_travel_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travel_Record',
            new_name='TravelRecord',
        ),
    ]
