# Generated by Django 4.1.2 on 2022-10-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_travel_record_travelrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrecord',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
