# Generated by Django 4.1.2 on 2022-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_travelrecord_arrived_at_travelrecord_departed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='infection_probability',
            field=models.FloatField(default=0),
        ),
    ]
