# Generated by Django 4.1.2 on 2022-10-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_infection_probability'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionPeroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected_from', models.DateTimeField(default=None, verbose_name='infection start time')),
                ('infected_to', models.DateTimeField(default=None, verbose_name='infection end time')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
