# Generated by Django 4.1.2 on 2022-10-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_location_remove_travelrecord_location_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infectionrecord',
            old_name='infected_from',
            new_name='infected_at',
        ),
        migrations.RemoveField(
            model_name='infectionrecord',
            name='infected_to',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='departed_at',
        ),
    ]
